language: ruby
rvm:
  - 1.9
  - 2.0
  - 2.1
  - jruby
  - rbx-2
  - ruby-head
  - jruby-head
matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head
  fast_finish: true
script: bundle exec rake -t metrics:coverage ci
before_install:
  - gem install bundler
